name: GitVersion Auto Release

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.11.0
      with:
        versionSpec: '5.x'

    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.11.0

    - name: Update .csproj with calculated version
      run: |
        VERSION=${{ steps.gitversion.outputs.nuGetVersionV2 }}
        sed -i "s|<Version>.*</Version>|<Version>$VERSION</Version>|" DotnetSemverDemo.csproj

    - name: Build the project
      run: dotnet build -c Release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.gitversion.outputs.semVer }}
        name: Release v${{ steps.gitversion.outputs.semVer }}
        body: "Automated release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
